/**
 * ============================================================
 *  CRWN — MUSIC PLAYER ENGINE
 *  player.js — handles all audio logic, UI, and 45-sec preview
 *
 *  DO NOT EDIT THIS FILE unless you know JavaScript.
 *  To change songs, edit: js/songs.js
 * ============================================================
 */

(function () {
  'use strict';

  /* ── STATE ───────────────────────────────────────────── */
  let currentIndex = 0;
  let isPlaying = false;
  let previewTimer = null;
  let audio = new Audio();
  let progressInterval = null;
  let modalOpen = false;

  /* ── DOM REFS (set after DOMContentLoaded) ───────────── */
  let modal, backdrop, panel;
  let coverImg, trackTitle, trackAlbum;
  let progressFill, timeElapsed, timeLimit;
  let playBtn, prevBtn, nextBtn;
  let nowPlayingLabel;
  let tracklistEl;
  let purchaseBtnEl;

  /* ── INIT ────────────────────────────────────────────── */
  document.addEventListener('DOMContentLoaded', () => {
    buildPlayerHTML();
    cacheDOMRefs();
    buildTracklist();
    bindEvents();
    loadTrack(0, false); // load first track without playing
  });

  /* ── BUILD MODAL HTML ───────────────────────────────── */
  function buildPlayerHTML() {
    const el = document.createElement('div');
    el.innerHTML = `
    <!-- PLAYER MODAL -->
    <div class="player-modal" id="playerModal" role="dialog" aria-modal="true" aria-label="CRWN Music Player">
      <div class="player-backdrop" id="playerBackdrop"></div>
      <div class="player-panel">

        <!-- LEFT: NOW PLAYING -->
        <div class="player-left">
          <div class="now-playing-label paused" id="nowPlayingLabel">Now Playing</div>

          <div class="cover-wrap" id="coverWrap">
            <img src="" alt="Album Art" id="coverImg">
            ${PLAYER_CONFIG.showPreviewBadge ? '<div class="preview-badge">45-Sec Preview</div>' : ''}
          </div>

          <div class="track-info">
            <div class="track-title" id="trackTitle">—</div>
            <div class="track-album" id="trackAlbum">${PLAYER_CONFIG.albumTitle} · ${PLAYER_CONFIG.artistName}</div>
          </div>

          <!-- Progress -->
          <div class="progress-wrap">
            <div class="progress-bar-bg" id="progressBarBg">
              <div class="progress-fill" id="progressFill"></div>
            </div>
            <div class="progress-times">
              <span id="timeElapsed">0:00</span>
              <span class="time-limit" id="timeLimit">0:45 preview</span>
            </div>
          </div>

          <!-- Controls -->
          <div class="controls">
            <button class="ctrl-btn" id="prevBtn" aria-label="Previous">
              <svg viewBox="0 0 24 24"><path d="M6 6h2v12H6zm3.5 6 8.5 6V6z"/></svg>
            </button>
            <button class="ctrl-btn play-btn" id="playBtn" aria-label="Play">
              <svg id="playIcon" viewBox="0 0 24 24"><path d="M8 5v14l11-7z"/></svg>
              <svg id="pauseIcon" viewBox="0 0 24 24" style="display:none"><path d="M6 19h4V5H6v14zm8-14v14h4V5h-4z"/></svg>
            </button>
            <button class="ctrl-btn" id="nextBtn" aria-label="Next">
              <svg viewBox="0 0 24 24"><path d="M6 18l8.5-6L6 6v12zm2-8.14 4.96 2.14L8 14.14V9.86zM16 6h2v12h-2z"/></svg>
            </button>
          </div>

          <!-- Per-track purchase -->
          <a href="#" class="purchase-btn" id="purchaseBtn" target="_blank">
            <svg viewBox="0 0 24 24"><path d="M20 4H4c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2zm0 14H4v-6h16v6zm0-10H4V6h16v2z"/></svg>
            <span id="purchaseBtnLabel">Buy Track</span>
          </a>
        </div>

        <!-- RIGHT: TRACKLIST -->
        <div class="player-right">
          <div class="tracklist-header">
            <div>
              <div class="tracklist-title">${PLAYER_CONFIG.albumTitle}</div>
              <div class="tracklist-subtitle">${CRWN_SONGS.length} Tracks · ${PLAYER_CONFIG.artistName} · 45-sec previews</div>
            </div>
            <button class="close-btn" id="closeBtn" aria-label="Close player">✕</button>
          </div>

          <div class="tracklist" id="tracklist"></div>

          <div class="tracklist-footer">
            <span class="preview-note">Previews auto-stop at 45 seconds</span>
            <a href="#" class="album-purchase" id="albumPurchaseBtn">
              ♛ Buy Full Album
            </a>
          </div>
        </div>

      </div>
    </div>`;
    document.body.appendChild(el.firstElementChild);
  }

  /* ── CACHE DOM REFS ─────────────────────────────────── */
  function cacheDOMRefs() {
    modal          = document.getElementById('playerModal');
    backdrop       = document.getElementById('playerBackdrop');
    coverImg       = document.getElementById('coverImg');
    trackTitle     = document.getElementById('trackTitle');
    trackAlbum     = document.getElementById('trackAlbum');
    progressFill   = document.getElementById('progressFill');
    timeElapsed    = document.getElementById('timeElapsed');
    timeLimit      = document.getElementById('timeLimit');
    playBtn        = document.getElementById('playBtn');
    prevBtn        = document.getElementById('prevBtn');
    nextBtn        = document.getElementById('nextBtn');
    nowPlayingLabel = document.getElementById('nowPlayingLabel');
    tracklistEl    = document.getElementById('tracklist');
    purchaseBtnEl  = document.getElementById('purchaseBtn');
    document.getElementById('closeBtn').addEventListener('click', closeModal);
    backdrop.addEventListener('click', closeModal);
  }

  /* ── BUILD TRACKLIST ROWS ────────────────────────────── */
  function buildTracklist() {
    tracklistEl.innerHTML = '';
    CRWN_SONGS.forEach((song, i) => {
      const row = document.createElement('div');
      row.className = 'track-row';
      row.dataset.index = i;
      row.innerHTML = `
        <div class="track-num">
          <span class="num-static">${String(i + 1).padStart(2, '0')}</span>
          <div class="bars">
            <div class="bar" style="height:4px"></div>
            <div class="bar" style="height:8px"></div>
            <div class="bar" style="height:4px"></div>
          </div>
        </div>
        <div class="track-thumb">
          <img src="${song.coverArt}" alt="${song.title}"
               onerror="this.src='${PLAYER_CONFIG.fallbackCover}'">
        </div>
        <div class="track-meta">
          <div class="track-name">${song.title}</div>
          <div class="track-album-label">${song.album}</div>
        </div>
        <div class="track-duration">${song.duration}</div>
      `;
      row.addEventListener('click', () => {
        if (currentIndex === i && isPlaying) {
          pauseTrack();
        } else {
          loadTrack(i, true);
        }
      });
      tracklistEl.appendChild(row);
    });
  }

  /* ── BIND EVENTS ─────────────────────────────────────── */
  function bindEvents() {
    // Trigger buttons
    document.querySelectorAll('[data-player-open]').forEach(btn => {
      btn.addEventListener('click', (e) => {
        e.preventDefault();
        openModal();
      });
    });

    // Controls
    playBtn.addEventListener('click', togglePlay);
    prevBtn.addEventListener('click', prevTrack);
    nextBtn.addEventListener('click', nextTrack);

    // Progress bar scrub
    document.getElementById('progressBarBg').addEventListener('click', (e) => {
      const rect = e.currentTarget.getBoundingClientRect();
      const pct = (e.clientX - rect.left) / rect.width;
      const maxTime = PLAYER_CONFIG.previewDuration;
      const newTime = (audio.currentTime || 0) + (pct * maxTime - ((audio.currentTime - CRWN_SONGS[currentIndex].previewStart) || 0));
      const startTime = CRWN_SONGS[currentIndex].previewStart || 0;
      audio.currentTime = startTime + (pct * maxTime);
    });

    // Audio events
    audio.addEventListener('timeupdate', onTimeUpdate);
    audio.addEventListener('ended', onEnded);
    audio.addEventListener('error', onAudioError);

    // Keyboard close
    document.addEventListener('keydown', (e) => {
      if (e.key === 'Escape' && modalOpen) closeModal();
      if (e.key === ' ' && modalOpen) { e.preventDefault(); togglePlay(); }
      if (e.key === 'ArrowRight' && modalOpen) nextTrack();
      if (e.key === 'ArrowLeft' && modalOpen) prevTrack();
    });

    // Album purchase
    document.getElementById('albumPurchaseBtn').addEventListener('click', (e) => {
      // Link to a general album purchase URL — update in songs.js or here
      window.open(CRWN_SONGS[currentIndex].purchaseUrl || '#', '_blank');
    });
  }

  /* ── MODAL OPEN / CLOSE ─────────────────────────────── */
  function openModal() {
    modal.classList.add('open');
    modalOpen = true;
    document.body.style.overflow = 'hidden';
  }

  function closeModal() {
    modal.classList.remove('open');
    modalOpen = false;
    document.body.style.overflow = '';
    // Don't stop audio on close — let it continue
  }

  /* ── LOAD TRACK ─────────────────────────────────────── */
  function loadTrack(index, autoPlay) {
    currentIndex = index;
    const song = CRWN_SONGS[index];

    // Update UI
    coverImg.src = song.coverArt;
    coverImg.onerror = () => { coverImg.src = PLAYER_CONFIG.fallbackCover; };
    trackTitle.textContent = song.title;
    trackAlbum.textContent = `${song.album} · ${PLAYER_CONFIG.artistName}`;
    timeLimit.textContent = `0:${String(PLAYER_CONFIG.previewDuration).padStart(2,'0')} preview`;

    // Purchase button
    purchaseBtnEl.href = song.purchaseUrl || '#';
    document.getElementById('purchaseBtnLabel').textContent = song.purchaseLabel || 'Buy Track';

    // Audio
    audio.src = song.audioSrc;
    audio.currentTime = song.previewStart || 0;

    // Reset progress
    setProgress(0);
    timeElapsed.textContent = '0:00';

    // Highlight active row
    updateActiveRow(index);

    if (autoPlay) {
      playTrack();
    } else {
      setPlayState(false);
    }
  }

  /* ── PLAY / PAUSE ────────────────────────────────────── */
  function playTrack() {
    clearPreviewTimer();
    const song = CRWN_SONGS[currentIndex];
    const startTime = song.previewStart || 0;

    // If audio hasn't started from the correct point, reset
    if (audio.currentTime < startTime || audio.currentTime >= startTime + PLAYER_CONFIG.previewDuration) {
      audio.currentTime = startTime;
    }

    audio.play().then(() => {
      setPlayState(true);
      startProgressInterval();
      startPreviewTimer();
    }).catch(err => {
      console.warn('Audio play failed:', err);
      // Autoplay blocked — show message
      setPlayState(false);
    });
  }

  function pauseTrack() {
    audio.pause();
    setPlayState(false);
    clearProgressInterval();
    clearPreviewTimer();
  }

  function togglePlay() {
    if (isPlaying) {
      pauseTrack();
    } else {
      playTrack();
    }
  }

  function prevTrack() {
    const newIndex = currentIndex === 0 ? CRWN_SONGS.length - 1 : currentIndex - 1;
    loadTrack(newIndex, isPlaying);
  }

  function nextTrack() {
    const newIndex = (currentIndex + 1) % CRWN_SONGS.length;
    loadTrack(newIndex, isPlaying);
  }

  /* ── PREVIEW TIMER (stops at 45s) ───────────────────── */
  function startPreviewTimer() {
    clearPreviewTimer();
    const song = CRWN_SONGS[currentIndex];
    const startTime = song.previewStart || 0;
    const endTime = startTime + PLAYER_CONFIG.previewDuration;
    const remaining = (endTime - audio.currentTime) * 1000;

    previewTimer = setTimeout(() => {
      pauseTrack();
      audio.currentTime = song.previewStart || 0;
      setProgress(100);
      timeElapsed.textContent = formatTime(PLAYER_CONFIG.previewDuration);
      // Flash purchase button
      flashPurchaseBtn();
    }, Math.max(0, remaining));
  }

  function clearPreviewTimer() {
    if (previewTimer) {
      clearTimeout(previewTimer);
      previewTimer = null;
    }
  }

  function flashPurchaseBtn() {
    purchaseBtnEl.style.background = 'var(--gold)';
    purchaseBtnEl.style.color = 'var(--black)';
    setTimeout(() => {
      purchaseBtnEl.style.background = '';
      purchaseBtnEl.style.color = '';
    }, 1500);
  }

  /* ── PROGRESS BAR ────────────────────────────────────── */
  function startProgressInterval() {
    clearProgressInterval();
    progressInterval = setInterval(updateProgress, 100);
  }

  function clearProgressInterval() {
    if (progressInterval) {
      clearInterval(progressInterval);
      progressInterval = null;
    }
  }

  function updateProgress() {
    const song = CRWN_SONGS[currentIndex];
    const startTime = song.previewStart || 0;
    const elapsed = Math.max(0, audio.currentTime - startTime);
    const pct = Math.min(100, (elapsed / PLAYER_CONFIG.previewDuration) * 100);
    setProgress(pct);
    timeElapsed.textContent = formatTime(elapsed);
  }

  function setProgress(pct) {
    progressFill.style.width = pct + '%';
  }

  function onTimeUpdate() {
    const song = CRWN_SONGS[currentIndex];
    const endTime = (song.previewStart || 0) + PLAYER_CONFIG.previewDuration;
    // Safety: stop if past end (in case timer was delayed)
    if (audio.currentTime >= endTime) {
      pauseTrack();
      setProgress(100);
    }
  }

  function onEnded() {
    setPlayState(false);
    clearProgressInterval();
    clearPreviewTimer();
    if (PLAYER_CONFIG.autoPlayNext) {
      nextTrack();
    }
  }

  function onAudioError() {
    console.warn('Audio error — check file path in songs.js:', CRWN_SONGS[currentIndex].audioSrc);
    setPlayState(false);
    timeElapsed.textContent = 'File missing';
  }

  /* ── UI STATE ────────────────────────────────────────── */
  function setPlayState(playing) {
    isPlaying = playing;
    document.getElementById('playIcon').style.display = playing ? 'none' : 'block';
    document.getElementById('pauseIcon').style.display = playing ? 'block' : 'none';
    document.getElementById('coverWrap').classList.toggle('spinning', playing);
    nowPlayingLabel.classList.toggle('paused', !playing);

    const activeRow = tracklistEl.querySelector('.track-row.active');
    if (activeRow) activeRow.classList.toggle('playing', playing);
  }

  function updateActiveRow(index) {
    tracklistEl.querySelectorAll('.track-row').forEach((row, i) => {
      row.classList.toggle('active', i === index);
      row.classList.remove('playing');
    });
    // Scroll into view
    const activeRow = tracklistEl.querySelectorAll('.track-row')[index];
    if (activeRow) {
      activeRow.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
    }
  }

  /* ── HELPERS ─────────────────────────────────────────── */
  function formatTime(secs) {
    const s = Math.floor(secs);
    return `${Math.floor(s / 60)}:${String(s % 60).padStart(2, '0')}`;
  }

})();
